-- PATCH_ID: 20260216_095317579_create_user
-- PATCH_TYPE: SCHEMA
-- PATCH_CLASS: REVERSIBLE

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ROLLBACK:
-- DROP TABLE users;
